### ISSUE TITLE
Build breaks with latest Rollup

### ISSUE THREAD

**Issue by curran** [d3/d3-time#12]
After upgrading to Rollup 0.27.0 (on d3-time 0.2.5), I see the following error:

```
A module cannot have multiple exports with the same name ('utcSecond')
Error: A module cannot have multiple exports with the same name ('utcSecond')
    at /Users/curran/repos/reactive-vis/node_modules/rollup/src/Module.js:144:13
    at Array.forEach (native)
    at Module.addExport (/Users/curran/repos/reactive-vis/node_modules/rollup/src/Module.js:139:21)
    at /Users/curran/repos/reactive-vis/node_modules/rollup/src/Module.js:183:51
    at Array.forEach (native)
    at Module.analyse (/Users/curran/repos/reactive-vis/node_modules/rollup/src/Module.js:181:19)
    at new Module (/Users/curran/repos/reactive-vis/node_modules/rollup/src/Module.js:59:8)
    at /Users/curran/repos/reactive-vis/node_modules/rollup/src/Bundle.js:188:20
```

Indeed `utcSecond` is being exported twice:

[Line 38](https://github.com/d3/d3-time/blob/914e7b4a4be5b45e316451e353da13285b80a15d/index.js#L38)

```js
export var utcSecond = second;
```

[Line 70](https://github.com/d3/d3-time/blob/914e7b4a4be5b45e316451e353da13285b80a15d/index.js#L70)

```js
export {
  ...
  utcSecond,
  ...
};
```

**Comment by curran** [comment]
Here's a PR that fixes this https://github.com/d3/d3-time/pull/13
